### ISSUE TITLE
Pull request ongelma

### ISSUE THREAD

**Issue by aleekaup2** [JYU-IBA/potku#156]
Tein sellaisen virheen että tein ja mergetin oman forkin master branchiin noita pull requesteja, jotta olisin voinut testailla useampia uusia muutoksia kerralla ilman että mergetän niitä vielä JYU-IBA / potku :n master branchiin. Tämä kuitenkin sotki JYU-IBA / potku: n pull requestit siten että joissain pull requesteissa on mukana muiden pull requestien muutoksia. Esim. https://github.com/JYU-IBA/potku/pull/145

En ymmärrä miksi minun forkin muuttaminen muuttaisi sellaisiakin pull requesteja joita ei ole edes tehty minun forkista. 

Osaan välttää tätä jatkossa siten etten koske oman forkin master branchiin, mutta mikä olisi nyt järkevin tapa korjata pull requestit vastaamaan alkuperäisiä?

**Comment by jaakkojulin** [comment]
Omassa forkissa työskentely ei ole ongelma sinällään.

Pull request haluaa vain yhdistää kaksi haaraa (vähän kauniimpi tapa tehdä merge yhteistyössä muiden ihmisten kanssa), myös forkkien yli. Sinun olisi siis pitänyt yhdistää potkun master-branchia omaan forkkiisi (git merge), jossa sinulla on muutoksia omissa haaroissasi. Näin kun olet lopulta valmis, pull request sinun haarastasi toimii. Omia muutoksia on syytä pitää ajan tasalla muiden tekemien muutosten kanssa (git pull jne), pienet erot onnistuvat myös pull requestin kautta.

Sen lisäksi tuolla on mergetetty ihan mitä sattuu ihan minne sattuu, en ota selvää. Pull requesteja ei saa olla auki kovin montaa yhdeltä ihmisteltä kerralla!

Esimerkiksi #145 yhteydessä on käynyt niin, että tiedostoa dialogs/simulation/layer_properties.py on lopulta muokattu kahdessa paikassa yht'aikaa. Helpointa on katsoa kumpi on parempi, jos ero ei ole iso. Mutta aina mergetettävä haara ajan tasalle Potkun päähaaran kanssa!

Joissain tapauksissa voi olla selkeämpää poistaa pull requesteja ja valikoida tiettyjä alkuperäisiä committeja (git cherry-pick) ja tuoda muutoksia sitä kautta nykyisen masterin päälle. Testaa ennen pull requestia.
