### ISSUE TITLE
Files without cut-files should raise an error

### ISSUE THREAD

**Issue by jkpnen** [JYU-IBA/potku#212]
There should be a check that gives a warning if chosen element(s) on the GUI do not have cut-file(s).

![chosen_elements_on_gui](https://user-images.githubusercontent.com/82767802/141965798-62a39f4d-a551-40b8-bea3-6080b8c2f5d6.png)

**Comment by Huojuu** [comment]
Was it so that this feature should notify user if H1.eff is imported even if H1.cut file does not exist?

This feature in its current form breaks the efficiency plotting window (Cause of issue #250 ).
