### ISSUE TITLE
ScientificSpinbox looks and behaves differently than normal spinboxes

### ISSUE THREAD

**Issue by tpitkanen** [JYU-IBA/potku#214]
Two different spinboxes are confusing from a user perspective. The following differences should be unified:

|              | Spinbox    | ScientificSpinbox |
|--------------|------------|-------------------|
| Scrollable   | yes        | no                |
| Font size    | smaller    | larger            |
| Edit buttons | inside box | outside box       |

`ScientificSpinbox` is defined in **widgets/scientific_spinbox.py** and **ui_files/ui_scientific_spinbox_widget.ui**. `Spinbox` comes directly from Qt.

![scientific spinbox differences](https://user-images.githubusercontent.com/55845778/142015244-a52fc43a-65ef-4b23-abb4-4981a07dae2c.png)

**Comment by tpitkanen** [comment]
@mlaitin : spinboxes should not be scrollable

**Comment by jussiks** [comment]
Inheriting from [QAbstractSpinBox ](https://doc.qt.io/qt-5/qabstractspinbox.html) should fix the layout issues.

**Comment by jussiks** [comment]
> Inheriting from [QAbstractSpinBox ](https://doc.qt.io/qt-5/qabstractspinbox.html) should fix the layout issues.

Actually inheriting from QDoubleSpinBox is simpler as we only need to implement our own step function and value formatting.
