### ISSUE TITLE
Recoil elements will not be removed

### ISSUE THREAD

**Issue by jkpnen** [JYU-IBA/potku#233]
Recoil elements will not be removed when the corresponding element is removed.

![removing_selected_element](https://user-images.githubusercontent.com/82767802/143589534-893be52f-7c31-467a-80e8-e5ce18ac171a.png)
![after_removing_element](https://user-images.githubusercontent.com/82767802/143589531-9df3dbb0-318b-4e1b-b61a-f5b0e4b65dda.png)

**Comment by jussiks** [comment]
This looks like a duplicate of #13.

**Comment by samivout** [comment]
Closing duplicate, I'm working on the original issue.
