### ISSUE TITLE
Remove unnecessary initializations of GlobalSettings instances

### ISSUE THREAD

**Issue by jussiks** [JYU-IBA/potku#244]
Both `GetEspe` and `RecoilElement` create temporary `GlobalSettings` objects to get a default value for reference density in case `None` is provided as a value.:

https://github.com/JYU-IBA/potku/blob/f7c499ba6a7fb215a3ff216d15e11eb272b4bdea/modules/get_espe.py#L85-L88
https://github.com/JYU-IBA/potku/blob/f7c499ba6a7fb215a3ff216d15e11eb272b4bdea/modules/recoil_element.py#L81-L84

There are two things that can happen when initializing `GlobalSettings` without parameters:
- If the file `/<home folder>/potku/potku2.ini` exists, reference density is parsed from the file along with all the other settings
- If the file does not exist, new file is saved with default settings

We do not want these kinds of extra side effects when initializing `GetEspe` or `RecoilElement` objects.

## How does this affect Potku

As far as I can see, there is no way for `None` to be passed down to either `__init__` method during regular use of Potku. The only place where reference density is passed to `RecoilElement.__init__` is in the `RecoilElement.from_file` method and that method would crash on line 517 if the value was `None`:
https://github.com/JYU-IBA/potku/blob/f7c499ba6a7fb215a3ff216d15e11eb272b4bdea/modules/recoil_element.py#L515-L517

Some unit tests do end up passing `None` to `GetEspe` but otherwise reference densities are just taken from a recoil elements:
https://github.com/JYU-IBA/potku/blob/f7c499ba6a7fb215a3ff216d15e11eb272b4bdea/modules/element_simulation.py#L889

So for regular users, this is not really an issue (except for the fact that the default reference density setting in the global settings is currently useless...).

## How to improve things

- set the default reference density to either `GlobalSettings.DEFAULT_REF_DENSITY` or `profile.REFERENCE_DENSITY` (what's the difference here?):
```python
class RecoilElement(MCERDParameterContainer, Serializable):
    def __init__(
        self,
        ...,
        reference_density=GlobalSettings.DEFAULT_REF_DENSITY,
        ...):
```
- remove initialization of `GlobalSettings` instances from both `__init__` methods
- whenever creating new `RecoilElements` outside of `RecoilElement.from_file`, use the current GlobalSettings object to supply the default value:
```python
settings: GlobalSettings = self.simulation.request.global_settings
recoil_element = RecoilElement(
    element, points, color, rec_type=rec_type,
    reference_density=settings.get_default_reference_density()
)
```

**Comment by tpitkanen** [comment]
> - set the default reference density to either GlobalSettings.DEFAULT_REF_DENSITY or profile.REFERENCE_DENSITY (what's the difference here?):

Those are unrelated: #241. The one in `Profile` is used for converting units for depth profile plot (if I remember correctly), while the other one is used for simulations.
