### ISSUE TITLE
The apply button might cause unwanted changes when cancelling

### ISSUE THREAD

**Issue by jkpnen** [JYU-IBA/potku#248]
When the user press the apply button and the cancel button after it has the same effect as if the user had pressed the OK button.

In my opinion it is not so clear to the user what that apply button does. Should there be a separate confirmation box for it or OK?

Feel free to discuss. Especially @mlaitin 

![apply_button](https://user-images.githubusercontent.com/82767802/151196260-54768f72-4ac6-4809-a9d3-c6d839b0826e.PNG)

**Comment by tpitkanen** [comment]
@mlaitin: "This behavior is fine and intended."
