### ISSUE TITLE
shapely 1.8.1. causes issues on macOS

### ISSUE THREAD

**Issue by tpitkanen** [JYU-IBA/potku#264]
## Description

macOS bundle of Potku fails to start and complains about `Could not find lib geos_c or load any of its variants ...` when built with `shapely` 1.8.1. There are geos files in the listed directory, but they are named differently.

## Resolution

Downgrading `shapely` to 1.7.1 works.

**Comment by tleppala** [comment]
With python version update to 3.10 also shapely is updated to newer version, that does work with pyinstaller
