### ISSUE TITLE
Top menu may be initially stuck on macOS

### ISSUE THREAD

**Issue by tpitkanen** [JYU-IBA/potku#265]
## Description

The top menu with `File`, `Tools` etc. options seems to be stuck after opening Potku. The toolbar items don't react to clicks.

This may just be an issue on the Mac I'm using, considering it also gets stuck on shutdown every now and then.

The issue occured on today's bundle of Potku I made. It may have been there earlier too.

## Workaround

Swiping away from Potku (to a different "desktop", I don't know the macOS lingo for this) and back seems to fix it.

**Comment by jaakkojulin** [comment]
I don't have this issue with this bundle (potku_mac_20220331.zip) or any other version. macOS Monterey 12.2.1.
