### ISSUE TITLE
Selection information on bottom right of ToFE histogram doesn't show element or number of points

### ISSUE THREAD

**Issue by samivout** [JYU-IBA/potku#293]
A previous pull request #270 should've implemented this feature. The idea is that when the mouse cursor is inside an element selection, the UI would show the name of the element and number of points inside that selection.  This information would be shown next to the coordinates in the bottom right of the ToFE histogram window.

I do not know if this feature has ever worked, but regardless at the moment it does not work. The code that should've implemented this feature has been merged to master earlier in the now closed pull request #270

On a quick glance the issue seems to be with `self.mpl_toolbar.mode = str_text` on line 1027 in `widgets/matplotlib/measurement/tofe_histogram.py`. Additionally I take that the currently selected tool's name should display continuously next to the coordinates, but the tool's name is wiped immediately after moving the mouse cursor on the histogram.

**Comment by tleppala** [comment]
Element is highlighted it the legend, Pull request #311 shows points inside selection in the title of the window when selection is selected. Currently coordinates and point value shown is coming from matplotlib internals.
